In [3]:
import pandas as pd
import numpy as np

Este documento recoge una serie de ejercicios relacionados con el Data Set Titanic. 
A lo largo del mismo se irán viendo ejercicios con ligera compljidad gradual, desde únicamente cargar archivos hasta la búsqueda de datos específicos.

1. Vuelve a cargar lo datos de `data/titanic.csv`.

2. Vamos a establecer como índice el campo **Name**

3. Vamos a añadir una nueva columna, que sea **adult** y que tenga el valor True para todas las filas donde el campus **Age** sera mayor que 18.

4. ¿Cuántos menores de edad había abordo?

**Nota**: Si usamos la función `sum()` sobre una columna booleana, nos devuelve el número total de `Trues`.

In [6]:
#1º Ejercicio 
# Es capaz de leer desde un fichero local (ruta relativa desde la libreta o ruta absoluta)

df_titanic = pd.read_csv(r'C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\Titanic.csv')  # usamos los parámetros por defecto
df_titanic

,Name,PClass,Age,Sex,Survived,SexCode
0,"Allen, Miss Elisabeth Walton",1st,29.00,female,1,1
1,"Allison, Miss Helen Loraine",1st,2.00,female,0,1
2,"Allison, Mr Hudson Joshua Creighton",1st,30.00,male,0,0
3,"Allison, Mrs Hudson JC (Bessie Waldo Daniels)",1st,25.00,female,0,1
4,"Allison, Master Hudson Trevor",1st,0.92,male,1,0
...,...,...,...,...,...,...
1308,"Zakarian, Mr Artun",3rd,27.00,male,0,0
1309,"Zakarian, Mr Maprieder",3rd,26.00,male,0,0
1310,"Zenni, Mr Philip",3rd,22.00,male,0,0
1311,"Lievens, Mr Rene",3rd,24.00,male,0,0
1312,"Zimmerman, Leo",3rd,29.00,male,0,0

In [7]:
#Ejejercicio 2
df_titanic.set_index('Name', inplace=True)
df_titanic.head(2)

                             PClass   Age     Sex  Survived  SexCode
Name
Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
Allison, Miss Helen Loraine     1st   2.0  female         0        1

In [8]:
#Ejercicio 3
df_titanic['Adult']=df_titanic['Age']>18
df_titanic[['Age','Adult']].head(10)

                                                 Age  Adult
Name
Allen, Miss Elisabeth Walton                   29.00   True
Allison, Miss Helen Loraine                     2.00  False
Allison, Mr Hudson Joshua Creighton            30.00   True
Allison, Mrs Hudson JC (Bessie Waldo Daniels)  25.00   True
Allison, Master Hudson Trevor                   0.92  False
Anderson, Mr Harry                             47.00   True
Andrews, Miss Kornelia Theodosia               63.00   True
Andrews, Mr Thomas, jr                         39.00   True
Appleton, Mrs Edward Dale (Charlotte Lamson)   58.00   True
Artagaveytia, Mr Ramon                         71.00   True

In [12]:
#Ejericicio 4
df_menores_edad=df_titanic[df_titanic['Adult']==False].shape[0] 
print('Había',df_menores_edad,'menores de edad en el Titanic.')

Había 683 menores de edad en el Titanic.

In [ ]:
#Ejercicio 4 otra forma
df_titanic.adult.value_counts()
len(df_titanic) - df_titanic.adult.sum()

np.int64(683)

1. ¿Cuántas Clases únicas hay? ¿Cuáles son?

2. ¿Qué clase tiene más personas?

3. Crear un `Dataframe` que contenga la clase con más personas y todas aquellas que sea menor de edad.

4. ¿Cómo se llama el capitán? Encuéntratalo y accede a su nombre.

In [29]:
#Ejercicio 1 - Clases
df_titanic['PClass'].unique()

array(['1st', '2nd', '*', '3rd'], dtype=object)

In [30]:
df_titanic['PClass'].nunique()

4

In [31]:
#Ejercicio 2 - Clase con más personas
df_titanic['PClass'].value_counts().idxmax()

'3rd'

In [33]:
#3 Ejercicio- Crear un Dataframe que contenga la clase con más personas y todas aquellas que sea menor de edad.
df_ejercicio3=df_titanic.loc[(df_titanic['PClass']=='3rd')&(df_titanic['Age'] < 18)]
df_ejercicio3

,PClass,Age,Sex,Survived,SexCode,Adult,adult
Name,,,,,,,
"Abbott, Master Eugene Joseph",3rd,13.00,male,0,0,False,False
"Abbott, Mr Rossmore Edward",3rd,16.00,male,0,0,False,False
"Abelseth, Miss Anna Karen",3rd,16.00,female,1,1,False,False
"Aks, Master Philip",3rd,0.83,male,1,0,False,False
"Allum, Mr Owen George",3rd,17.00,male,0,0,False,False
"Andersson, Miss Ebba Iris",3rd,6.00,female,0,1,False,False
"Andersson, Miss Ellis Anna Maria",3rd,2.00,female,0,1,False,False
"Andersson, Miss Erna",3rd,17.00,female,1,1,False,False
"Andersson, Miss Ingeborg Constancia",3rd,9.00,female,0,1,False,False
"Andersson, Miss Sigrid Elizabeth",3rd,11.00,female,0,1,False,False
"Andersson, Master Sigvard Harald Elias",3rd,4.00,male,0,0,False,False
"Asplund, Master Carl Edgar",3rd,5.00,male,0,0,False,False
"Asplund, Master Clarence Gustaf Hugo",3rd,9.00,male,0,0,False,False
"Aspland, Master Edvin Rojj Felix",3rd,3.00,male,1,0,False,False
"Asplund, Master Filip Oscar",3rd,13.00,male,0,0,False,False
"Asplund, Miss Lillian Gertrud",3rd,5.00,female,1,1,False,False
"Attalah, Miss Malaka",3rd,17.00,female,0,1,False,False
"Baclini, Miss Eugenie",3rd,3.00,female,1,1,False,False
"Banoura, Miss Ayout",3rd,15.00,female,1,1,False,False
"Boulos, Master Akar",3rd,6.00,male,0,0,False,False
"Boulos, Miss Laura",3rd,9.00,female,0,1,False,False
"Calic, Mr Peter",3rd,17.00,male,0,0,False,False
"Carr, Miss Helen",3rd,16.00,female,1,1,False,False
"Coutts, Master Neville",3rd,3.00,male,1,0,False,False
"Coutts, Master William Leslie",3rd,9.00,male,1,0,False,False
"Cribb, Miss Laura Alice",3rd,17.00,female,1,1,False,False
"Danbom, Master Gilbert Sigvard Emanuel",3rd,0.33,male,0,0,False,False
"Davies, Mr Joseph",3rd,17.00,male,0,0,False,False
"Dean, Master Bertram Vere",3rd,1.00,male,1,0,False,False
"Dean, Miss Elizabeth Gladys (Millvena)",3rd,0.17,female,1,1,False,False
"Eklund, Mr Hans Linus",3rd,16.00,male,0,0,False,False
"Emanuel, Miss Virginia Ethel",3rd,5.00,female,1,1,False,False
"Ford, Miss Maggie",3rd,9.00,female,0,1,False,False
"Ford, Mr Neil Watson",3rd,16.00,male,0,0,False,False
"Gilnagh, Miss Katie",3rd,16.00,female,1,1,False,False
"Goldsmith, Master Frank John William",3rd,9.00,male,1,0,False,False
"Goodwin, Mr Charles E",3rd,14.00,male,0,0,False,False
"Goodwin, Miss Lillian A",3rd,16.00,female,0,1,False,False
"Goodwin, Master Harold V",3rd,9.00,male,0,0,False,False
"Goodwin, Miss Jessie A",3rd,10.00,female,0,1,False,False
"Goodwin, Master Sidney L",3rd,6.00,male,0,0,False,False
"Goodwin, Master William F",3rd,11.00,male,0,0,False,False
"Hagardon, Miss Kate",3rd,17.00,female,0,1,False,False
"Hirvonen, Miss Hildur E",3rd,2.00,female,0,1,False,False
"Jensen, Mr Svend Lauritz",3rd,17.00,male,0,0,False,False
"Johnson, Miss Eleanor Ileen",3rd,1.00,female,1,1,False,False
"Johnson, Master Harold Theodor",3rd,4.00,male,1,0,False,False
"Kallio, Mr Nikolai Erland",3rd,17.00,male,0,0,False,False
"Karun, Miss Anna Mary",3rd,4.00,female,1,1,False,False
"Kink, Miss Louise Gretchen",3rd,4.00,female,1,1,False,False
"Klasen, Miss Gertrud Emilia",3rd,1.50,female,0,1,False,False
"Sandstrom, Miss Beatrice Irene",3rd,1.50,female,0,1,False,False
"Van der Planke, Mr Leon",3rd,15.00,male,0,0,False,False
"Van Impe, Miss Catharine",3rd,10.00,female,0,1,False,False
"Vestrom, Miss Hulda Amanda Adolfina",3rd,14.00,female,0,1,False,False
"Yasbeck, Mrs Antoni",3rd,15.00,female,1,1,False,False

In [35]:
# 3 Ejercicio - otra forma
df_ejercicio3_prueba = df_titanic.loc[
    (df_titanic["PClass"] == df_titanic["PClass"].value_counts().idxmax()) &
    (df_titanic["Age"] < 18)
]
df_ejercicio3_prueba

,PClass,Age,Sex,Survived,SexCode,Adult,adult
Name,,,,,,,
"Abbott, Master Eugene Joseph",3rd,13.00,male,0,0,False,False
"Abbott, Mr Rossmore Edward",3rd,16.00,male,0,0,False,False
"Abelseth, Miss Anna Karen",3rd,16.00,female,1,1,False,False
"Aks, Master Philip",3rd,0.83,male,1,0,False,False
"Allum, Mr Owen George",3rd,17.00,male,0,0,False,False
"Andersson, Miss Ebba Iris",3rd,6.00,female,0,1,False,False
"Andersson, Miss Ellis Anna Maria",3rd,2.00,female,0,1,False,False
"Andersson, Miss Erna",3rd,17.00,female,1,1,False,False
"Andersson, Miss Ingeborg Constancia",3rd,9.00,female,0,1,False,False
"Andersson, Miss Sigrid Elizabeth",3rd,11.00,female,0,1,False,False
"Andersson, Master Sigvard Harald Elias",3rd,4.00,male,0,0,False,False
"Asplund, Master Carl Edgar",3rd,5.00,male,0,0,False,False
"Asplund, Master Clarence Gustaf Hugo",3rd,9.00,male,0,0,False,False
"Aspland, Master Edvin Rojj Felix",3rd,3.00,male,1,0,False,False
"Asplund, Master Filip Oscar",3rd,13.00,male,0,0,False,False
"Asplund, Miss Lillian Gertrud",3rd,5.00,female,1,1,False,False
"Attalah, Miss Malaka",3rd,17.00,female,0,1,False,False
"Baclini, Miss Eugenie",3rd,3.00,female,1,1,False,False
"Banoura, Miss Ayout",3rd,15.00,female,1,1,False,False
"Boulos, Master Akar",3rd,6.00,male,0,0,False,False
"Boulos, Miss Laura",3rd,9.00,female,0,1,False,False
"Calic, Mr Peter",3rd,17.00,male,0,0,False,False
"Carr, Miss Helen",3rd,16.00,female,1,1,False,False
"Coutts, Master Neville",3rd,3.00,male,1,0,False,False
"Coutts, Master William Leslie",3rd,9.00,male,1,0,False,False
"Cribb, Miss Laura Alice",3rd,17.00,female,1,1,False,False
"Danbom, Master Gilbert Sigvard Emanuel",3rd,0.33,male,0,0,False,False
"Davies, Mr Joseph",3rd,17.00,male,0,0,False,False
"Dean, Master Bertram Vere",3rd,1.00,male,1,0,False,False
"Dean, Miss Elizabeth Gladys (Millvena)",3rd,0.17,female,1,1,False,False
"Eklund, Mr Hans Linus",3rd,16.00,male,0,0,False,False
"Emanuel, Miss Virginia Ethel",3rd,5.00,female,1,1,False,False
"Ford, Miss Maggie",3rd,9.00,female,0,1,False,False
"Ford, Mr Neil Watson",3rd,16.00,male,0,0,False,False
"Gilnagh, Miss Katie",3rd,16.00,female,1,1,False,False
"Goldsmith, Master Frank John William",3rd,9.00,male,1,0,False,False
"Goodwin, Mr Charles E",3rd,14.00,male,0,0,False,False
"Goodwin, Miss Lillian A",3rd,16.00,female,0,1,False,False
"Goodwin, Master Harold V",3rd,9.00,male,0,0,False,False
"Goodwin, Miss Jessie A",3rd,10.00,female,0,1,False,False
"Goodwin, Master Sidney L",3rd,6.00,male,0,0,False,False
"Goodwin, Master William F",3rd,11.00,male,0,0,False,False
"Hagardon, Miss Kate",3rd,17.00,female,0,1,False,False
"Hirvonen, Miss Hildur E",3rd,2.00,female,0,1,False,False
"Jensen, Mr Svend Lauritz",3rd,17.00,male,0,0,False,False
"Johnson, Miss Eleanor Ileen",3rd,1.00,female,1,1,False,False
"Johnson, Master Harold Theodor",3rd,4.00,male,1,0,False,False
"Kallio, Mr Nikolai Erland",3rd,17.00,male,0,0,False,False
"Karun, Miss Anna Mary",3rd,4.00,female,1,1,False,False
"Kink, Miss Louise Gretchen",3rd,4.00,female,1,1,False,False
"Klasen, Miss Gertrud Emilia",3rd,1.50,female,0,1,False,False
"Sandstrom, Miss Beatrice Irene",3rd,1.50,female,0,1,False,False
"Van der Planke, Mr Leon",3rd,15.00,male,0,0,False,False
"Van Impe, Miss Catharine",3rd,10.00,female,0,1,False,False
"Vestrom, Miss Hulda Amanda Adolfina",3rd,14.00,female,0,1,False,False
"Yasbeck, Mrs Antoni",3rd,15.00,female,1,1,False,False

In [39]:
#4 Ejercicio 
df_titanic.loc[df_titanic['PClass']=='*'].iloc[0]

PClass          *
Age           NaN
Sex          male
Survived        0
SexCode         0
Adult       False
adult       False
Name: Jacobsohn Mr Samuel, dtype: object

EJERCICIOS EXTRA
**Ejercicio_1**: Calcula el porcentaje de hombres y mujeres que sobrevivieron.
**Ejercicio_2**: Calcula la edad promedio de los pasajeros que sobrevivieron y los que no sobrevivieron.
**Ejercicio_3**: 	Encuentra a los pasajeros cuyo nombre contiene “Miss” y que tienen menos de 30 años.
**Ejercicio_4**: Crea una nueva columna llamada AgeGroup que clasifique a los pasajeros en Niño (edad < 18) o Adulto (edad >= 18). Después calcula la proporción de supervivencia por grupo de edad (Niño vs. Adulto), ¿puedes sacar los posibles factores detrás de las diferencias?

In [43]:
df_titanic = df_titanic.reset_index()

df_titanic_male = df_titanic.loc[(df_titanic.Sex == 'male')] 
df_titanic_male.loc[df_titanic_male.Survived == 1]['Name'].count()/df_titanic_male.shape[0]

np.float64(0.16686251468860164)

In [42]:
percentage_female_survived = (
    df_titanic.loc[df_titanic["Sex"] == "female", "Survived"]
    .mean()
)
percentage_female_survived

np.float64(0.6666666666666666)

In [44]:
#Ejercicio_2
mean_age_survived =(
    df_titanic.loc[df_titanic['Survived']==1,'Age'].mean(
)
)
mean_age_survived

np.float64(29.35958466453674)

In [45]:
#No supervivientes
df_titanic.loc[df_titanic['Survived']==0]['Age'].mean()

np.float64(31.131670428893905)

In [46]:
#Ejercicio 3
df_titanic.loc[(df_titanic.Name.str.contains ('Miss')) & (df_titanic.Age< 30)]

,index,Name,PClass,Age,Sex,Survived,SexCode,Adult,adult
0,0,"Allen, Miss Elisabeth Walton",1st,29.0,female,1,1,True,True
1,1,"Allison, Miss Helen Loraine",1st,2.0,female,0,1,False,False
31,31,"Bowerman, Miss Elsie Edith",1st,22.0,female,1,1,True,True
49,49,"Carter, Miss Lucile Polk",1st,14.0,female,1,1,False,False
99,99,"Fortune, Miss Alice Elizabeth",1st,24.0,female,1,1,True,True
...,...,...,...,...,...,...,...,...,...
1188,1188,"Sandstrom, Miss Beatrice Irene",3rd,1.5,female,0,1,False,False
1263,1263,"Turja, Miss Anna Sofia",3rd,18.0,female,1,1,False,False
1269,1269,"Van der Planke, Miss Augusta",3rd,18.0,female,0,1,False,False
1276,1276,"Van Impe, Miss Catharine",3rd,10.0,female,0,1,False,False
1283,1283,"Vestrom, Miss Hulda Amanda Adolfina",3rd,14.0,female,0,1,False,False

In [47]:
#Ejercicio_4

df_titanic['AgeGroup'] = np.where(
    df_titanic['Age'].notna() & (df_titanic['Age'] < 18),
    'Niño',
    'Adulto'
)
df_titanic[['Age', 'AgeGroup']].head(10)

     Age AgeGroup
0  29.00   Adulto
1   2.00     Niño
2  30.00   Adulto
3  25.00   Adulto
4   0.92     Niño
5  47.00   Adulto
6  63.00   Adulto
7  39.00   Adulto
8  58.00   Adulto
9  71.00   Adulto