A lo largo de este archivo se trabajará con un dataFrame llamado fifa22.csv. Es n conjunto de datos sobre jugadores en el videojuego FIFA 2019.

In [1]:
import pandas as pd

df_fifa = pd.read_csv(r'C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\ejercicios\ejercicios\data\fifa24.csv')
df_fifa.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\edith\\OneDrive\\Documentos\\Universidad\\Máster IA\\T1-herramientas_programación\\ejercicios\\ejercicios\\data\\fifa24.csv'

## <font color="#004D7F"> <i class="fa fa-pencil-square-o" aria-hidden="true" style="color:#113D68"></i> Ejercicio</font>

1. Sabiendo que los datos son de 2024, crear una columna `birth_year` que sea el año de nacimiento, calculado como 2024 menos la edad de cada jugador.

2. Sobreescribir la columna `release_clause` para que indique el valor como tipo numérico en millones.
    - *Nota*: algunos valores están en millones (€10M) y otros en miles (€10K).
  
3. Aplica el mismo método que has realizado para `release_clause` para `value` y `wage`.

4. Crear una columna que sea `effort`, calculada como la diferencia de la columna `potential` menos `overall`. ¿Qué jugadores están en el top 10 respecto a `effort`?

5. Transforma la columna `height` y `weight` en números flotantes, indicando respectivamente la altura en metros y el peso en kilogramos.

    - **Nota 1**: 1 pie son `30.48` centímetros
    - **Nota 2**: 1 libra son `0.453592` kilogramos

In [ ]:
def price_to_number(x):
    if x[-1] == 'K':
        return float(x[1:-1])/1000
    if x[-1] == 'M':
        return float(x[1:-1])
    else:
        return float(x[1:])/1000000
def feet_to_cm(x):
    return float(x.replace("'", ".")) * 30.48
def pounds_to_kg(x):
    return float(x.replace("lbs", "")) * 0.453592

In [ ]:
df_fifa=( 
    df_fifa
        .assign(
            birth_year=lambda df: 2024 - df['age'],
            release_clause= lambda df: df.release_clause.map(price_to_number),
            wage= lambda df: df.wage.map(price_to_number),
            value= lambda df: df.value.map(price_to_number),
            effort= lambda df: df.potential - df.overall,
            height= lambda df: df.height.map(feet_to_cm),
            weight= lambda df: df.weight.map(pounds_to_kg)
        )
)

In [ ]:
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,position,club_joined,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,ST,"Jul 01, 2018",181.9656,75.001437,349.4,2024.0,2000,3
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,ST,"Jul 01, 2022",195.0720,93.997870,356.1,2027.0,2002,3
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,CM,"Aug 30, 2015",181.0512,75.001437,190.6,2025.0,1992,0
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,CF,"Jul 16, 2023",168.8592,67.000074,61.5,2025.0,1988,0
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,CF,"Jul 01, 2023",185.0136,80.997923,81.6,2026.0,1989,0

In [ ]:
df_fifa.nlargest(10, 'effort')

,id,name,age,nationality,overall,potential,club,league,value,wage,position,club_joined,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort
13413,271626,E. Tezgel,17,England,56,82,Stoke City,Championship,0.575,0.00095,ST,"Jul 01, 2022",181.9656,71.998658,1.700,2025.0,2007,26
14583,273574,L. Gunnerød,16,Norway,50,76,Stabæk,Eliteserien,0.170,0.00050,GK,"Jan 01, 2022",182.8800,69.998317,0.383,2025.0,2008,26
16879,269086,D. Lobban,16,Scotland,53,79,Aberdeen,Premiership,0.375,0.00050,CAM,"May 11, 2022",174.9552,67.997977,1.000,2024.0,2008,26
13112,276719,F. Marshall,17,Scotland,57,82,Aberdeen,Premiership,0.525,0.00050,CAM,"Jul 01, 2023",180.1368,64.999734,1.400,2024.0,2007,25
13710,271016,K. Kolanko,16,Poland,55,80,Górnik Zabrze,Ekstraklasa,0.400,0.00050,LM,"Jul 28, 2022",163.0680,58.998711,0.940,2024.0,2008,25
13711,274472,N. Lowe,17,England,55,80,Stoke City,Championship,0.400,0.00090,ST,"Jul 01, 2022",192.9384,77.001778,1.200,2024.0,2007,25
13712,276789,L. Ross,16,Scotland,55,80,Motherwell,Premiership,0.400,0.00050,RW,"Jun 30, 2022",177.0888,66.002172,1.100,2025.0,2008,25
16880,269085,L. Harvey,17,Scotland,53,78,Aberdeen,Premiership,0.300,0.00050,ST,"May 11, 2022",178.0032,69.998317,0.825,2024.0,2007,25
14166,272849,F. Tewelde,16,Norway,53,77,Odd,Eliteserien,0.300,0.00050,LM,"Dec 09, 2021",178.0032,73.998999,0.675,2025.0,2008,24
14167,275283,S. Jansson,17,Sweden,53,77,Häcken,Allsvenskan,0.275,0.00050,CDM,"Dec 31, 2022",184.0992,69.998317,0.633,2025.0,2007,24

**Ejercicio**: Crea una columna `overall_category` que asigne:
- Mediocre si el overall es menor a 60.
- Bueno si está entre 60 y 80.
- Elite si es mayor a 80.

In [ ]:
df_fifa=(
    df_fifa
    .assign(
        overall_category= lambda df: df.overall.map(
            lambda x: 'Mediocre' if x < 60 else
                      'Bueno' if x < 80 else 
                      'Elite' 
        )

    )
)
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,position,club_joined,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort,overall_category
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,ST,"Jul 01, 2018",181.9656,75.001437,349.4,2024.0,2000,3,Elite
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,ST,"Jul 01, 2022",195.0720,93.997870,356.1,2027.0,2002,3,Elite
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,CM,"Aug 30, 2015",181.0512,75.001437,190.6,2025.0,1992,0,Elite
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,CF,"Jul 16, 2023",168.8592,67.000074,61.5,2025.0,1988,0,Elite
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,CF,"Jul 01, 2023",185.0136,80.997923,81.6,2026.0,1989,0,Elite

**Ejercicio**: Crea una nueva columna llamada `age_group` que clasifique a los jugadores en:
- Joven si tienen menos de 23 años.
- Maduro si tienen entre 23 y 30 años.
- Veterano si tienen más de 30 años.

In [ ]:
df_fifa=(
    df_fifa
        .assign(
            age_group= lambda df: df.age.map(
                lambda x: 'Joven' if x < 23 else
                          'Maduro' if x < 30 else
                          'Veterano'
            )
        )
)
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,position,club_joined,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort,overall_category,age_group
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,ST,"Jul 01, 2018",181.9656,75.001437,349.4,2024.0,2000,3,Elite,Maduro
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,ST,"Jul 01, 2022",195.0720,93.997870,356.1,2027.0,2002,3,Elite,Joven
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,CM,"Aug 30, 2015",181.0512,75.001437,190.6,2025.0,1992,0,Elite,Veterano
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,CF,"Jul 16, 2023",168.8592,67.000074,61.5,2025.0,1988,0,Elite,Veterano
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,CF,"Jul 01, 2023",185.0136,80.997923,81.6,2026.0,1989,0,Elite,Veterano

**Ejercicio**: Calcula el salario anual de cada jugador (`wage_yearly`) usando su salario semanal `wage`.

In [ ]:
#Wage viene en semanas
df_fifa=(
    df_fifa
    .assign(
        wage_yearly= lambda df: df.wage*52
    )
)
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,...,club_joined,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort,overall_category,age_group,wage_yearly
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,...,"Jul 01, 2018",181.9656,75.001437,349.4,2024.0,2000,3,Elite,Maduro,11.960
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,...,"Jul 01, 2022",195.0720,93.997870,356.1,2027.0,2002,3,Elite,Joven,17.680
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,...,"Aug 30, 2015",181.0512,75.001437,190.6,2025.0,1992,0,Elite,Veterano,18.200
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,...,"Jul 16, 2023",168.8592,67.000074,61.5,2025.0,1988,0,Elite,Veterano,1.196
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,...,"Jul 01, 2023",185.0136,80.997923,81.6,2026.0,1989,0,Elite,Veterano,4.940

**Ejercicio**: Calcular el Índice de Masa Corporal (IMC) de los jugadores usando sus valores de peso y altura

- **Nota**: la fórmula del IMC es $IMC = peso (kg) / altura (m)^2$

In [ ]:
df_fifa=(
    df_fifa
        .assign(
            IMC= lambda df: df.weight / ( (df.height/100) **2 )
    )
)
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,...,height,weight,release_clause,club_contract_valid_until_year,birth_year,effort,overall_category,age_group,wage_yearly,IMC
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,...,181.9656,75.001437,349.4,2024.0,2000,3,Elite,Maduro,11.960,22.651189
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,...,195.0720,93.997870,356.1,2027.0,2002,3,Elite,Joven,17.680,24.701774
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,...,181.0512,75.001437,190.6,2025.0,1992,0,Elite,Veterano,18.200,22.880566
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,...,168.8592,67.000074,61.5,2025.0,1988,0,Elite,Veterano,1.196,23.497726
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,...,185.0136,80.997923,81.6,2026.0,1989,0,Elite,Veterano,4.940,23.662824

**Ejercicio**: Crea una nueva columna `club_acronym` que tome las primeras letras de cada palabra en el nombre del club (por ejemplo, “Paris Saint-Germain” → “PSG”).

In [ ]:
df_fifa=(
    df_fifa
        .assign(
            club_acronym= lambda df: df.club.map(
                lambda x: ''.join([word[0] for word in x.split()]).upper()
                #club_acronym=lambda df: df.club.map(lambda x: ''.join([i[0] for i in x.replace('-', ' ').split()])) --> otra forma de hacerlo
            )
        )
)
df_fifa.head()

,id,name,age,nationality,overall,potential,club,league,value,wage,...,weight,release_clause,club_contract_valid_until_year,birth_year,effort,overall_category,age_group,wage_yearly,IMC,club_acronym
0,231747,K. Mbappé,24,France,91,94,Paris Saint Germain,Ligue 1,181.5,0.230,...,75.001437,349.4,2024.0,2000,3,Elite,Maduro,11.960,22.651189,PSG
1,239085,E. Haaland,22,Norway,91,94,Manchester City,Premier League,185.0,0.340,...,93.997870,356.1,2027.0,2002,3,Elite,Joven,17.680,24.701774,MC
2,192985,K. De Bruyne,32,Belgium,91,91,Manchester City,Premier League,103.0,0.350,...,75.001437,190.6,2025.0,1992,0,Elite,Veterano,18.200,22.880566,MC
3,158023,L. Messi,36,Argentina,90,90,Inter Miami,Major League Soccer,41.0,0.023,...,67.000074,61.5,2025.0,1988,0,Elite,Veterano,1.196,23.497726,IM
4,165153,K. Benzema,35,France,90,90,Al Ittihad,Pro League,51.0,0.095,...,80.997923,81.6,2026.0,1989,0,Elite,Veterano,4.940,23.662824,AI

Responde las siguientes preguntas:

- 1. ¿Cuánto cuesta el jugador más valorado de cada equipo (queremos conocer el nombre)? Una vez obtenido el jugador más valorado de cada equipoo ordena de más valorado a menos valorado.
- 2. ¿Cuánto cuesta comprar de media cada jugador según su equipo y su posición de equipo? Específicamente muestra el equipo `Atlético de Madrid`.
- 3. ¿Cuál es el mínimo, máximo y la media de lo que cuestan comprar los jugadores por equipo y cuantos jugadores hay de cada equipo? Muestra la información obtenida para los equipos `FC Barcelona` u `Cádiz CF`.

In [ ]:
def most_value_player(df):
    return df.loc[df["value"] == df["value"].max()]
(
    df_fifa
    .groupby('club')
    .apply(most_value_player)
    [['name', 'value']]
    .sort_values('value', ascending=False)
)

C:\Users\edith\AppData\Local\Temp\ipykernel_16596\885559962.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(most_value_player)

                                    name   value
club
Manchester City     1         E. Haaland  185.00
Paris Saint Germain 0          K. Mbappé  181.50
Real Madrid         8           Vini Jr.  158.50
FC Bayern München   35        J. Musiala  134.50
Napoli              18        V. Osimhen  126.50
...                                  ...     ...
Curicó Unido        19287      M. Cortés    0.14
Astra               18813    M. Bolboașă    0.14
Pescara             19229  C. Del Grosso    0.12
Tianjin Quanjian FC 19384    Fang Jingqi    0.08
St. Pölten          18505  T. Vollnhofer    0.05

[938 rows x 2 columns]

In [ ]:
#Otro modo de hacerlo
(df_fifa
    .groupby('club')
    .apply(lambda df: df.loc[df["value"] == df["value"].max()])
    [['name', 'value']]
    .sort_values('value', ascending=False)
)

C:\Users\edith\AppData\Local\Temp\ipykernel_16596\3242943371.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda df: df.loc[df["value"] == df["value"].max()])

                                    name   value
club
Manchester City     1         E. Haaland  185.00
Paris Saint Germain 0          K. Mbappé  181.50
Real Madrid         8           Vini Jr.  158.50
FC Bayern München   35        J. Musiala  134.50
Napoli              18        V. Osimhen  126.50
...                                  ...     ...
Curicó Unido        19287      M. Cortés    0.14
Astra               18813    M. Bolboașă    0.14
Pescara             19229  C. Del Grosso    0.12
Tianjin Quanjian FC 19384    Fang Jingqi    0.08
St. Pölten          18505  T. Vollnhofer    0.05

[938 rows x 2 columns]

In [ ]:
#Pregunta 2
(
    df_fifa
    .groupby(['club', 'position'])
    .agg(
        avg_release_clause=('release_clause', 'mean'),
    )
    .loc['Atlético Madrid']
)

          avg_release_clause
position
CB                 30.357143
CDM                25.500000
CF                120.100000
CM                 55.475000
GK                 29.660000
LB                 34.933333
LM                 22.040000
RB                 51.200000
RM                 87.100000
ST                 72.900000

In [ ]:
#Ejercicio 3
def num_players(lista):
    return len(lista)
(
    df_fifa
    .groupby('club')
    .agg(
        max_release=('release_clause', 'max'),
        min_release=('release_clause', 'min'),
        avg_release=('release_clause', 'mean'),
        num_jugadores=('name', num_players)
    )
.loc[['FC Barcelona','Cádiz']]
)

              max_release  min_release  avg_release  num_jugadores
club
FC Barcelona        236.3        1.100    60.637838             37
Cádiz                43.1        0.945     8.304143             35

**Ejercicio**: ¿Cuántos jugadores hay en cada nacionalidad dentro de cada categoría de rendimiento (`overall_category`)?

In [ ]:
(
    df_fifa
    .groupby(['nationality', 'overall_category'])
    .agg(
        count=('overall', 'count')
    )
    .loc['Germany']
)

                  count
overall_category
Bueno              1018
Elite                33
Mediocre            207

Si se agrupan a los jugadores por posición, ?Cuál es el salario promedio para cada posición y quién tiene el salario más alto en cada una?

In [ ]:
(
    df_fifa
    .groupby('position')
    .agg(
        avg_wage_position=('wage', 'mean')
    )
)

          avg_wage_position
position
CAM                0.008161
CB                 0.008650
CDM                0.008673
CF                 0.020257
CM                 0.009370
GK                 0.005898
LB                 0.008049
LM                 0.006821
LW                 0.013814
LWB                0.006895
RB                 0.007805
RM                 0.007708
RW                 0.011343
RWB                0.007160
ST                 0.008877

In [ ]:
(
    df_fifa
    .groupby('position')
    .apply(lambda df: df.loc[df["wage"] == df["wage"].max()])  #Otra opción es = .apply(lambda x: x.loc[x['wage'].idxmax()])
    [['name', 'wage']]
    
)

C:\Users\edith\AppData\Local\Temp\ipykernel_16596\3701341293.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda df: df.loc[df["wage"] == df["wage"].max()])  #Otra opción es = .apply(lambda x: x.loc[x['wage'].idxmax()])

                           name   wage
position
CAM      23     Bruno Fernandes  0.260
CB       11          Rúben Dias  0.250
CDM      10               Rodri  0.250
CF       47           C. Nkunku  0.185
CM       2         K. De Bruyne  0.350
GK       6          T. Courtois  0.250
LB       14719     João Cancelo  0.250
LM       113          F. Chiesa  0.140
LW       8             Vini Jr.  0.310
LWB      211         F. Dimarco  0.082
RB       118          K. Walker  0.155
         246           Carvajal  0.155
RM       93            M. Diaby  0.105
RW       16            M. Salah  0.260
RWB      301        D. Dumfries  0.080
ST       1           E. Haaland  0.340
         5       R. Lewandowski  0.340

**Ejercicio**: 	Calcula por cada club:
- El salario total.
- El salario promedio.
- El jugador con el salario más alto en cada club.

In [ ]:
(
    df_fifa
    .groupby('club')
    .agg(
        total_wage=('wage', 'sum'),
        avg_wage=('wage', 'mean'),

)
)

                     total_wage  avg_wage
club
1860 München            0.04075  0.001455
9 de Octubre            0.00200  0.000500
AEK Athens              0.03045  0.000801
AFC Bournemouth         0.86600  0.027935
AFC Wimbledon           0.05600  0.001931
...                         ...       ...
Ümraniyespor            0.02400  0.003429
İstanbul Başakşehir     0.41100  0.012455
İstanbulspor            0.12250  0.003500
ŁKS Łódź                0.03245  0.001159
Śląsk Wrocław           0.06255  0.001787

[872 rows x 2 columns]

In [ ]:
(
    df_fifa
    .groupby('club')
    .apply(lambda df: df.loc[df["wage"] == df["wage"].max()])
    [['name', 'wage']]
)

C:\Users\edith\AppData\Local\Temp\ipykernel_16596\3982466432.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda df: df.loc[df["wage"] == df["wage"].max()])

                              name    wage
club
1860 München  5744      J. Verlaat  0.0030
              6896      A. Vrenezi  0.0030
9 de Octubre  15342       J. Pinos  0.0005
              15706       É. Cetré  0.0005
              15768       M. Lucas  0.0005
...                            ...     ...
ŁKS Łódź      8378         M. Flis  0.0020
              8382    K. Dankowski  0.0020
              9488      B. Szeliga  0.0020
Śląsk Wrocław 6605   Erik Expósito  0.0040
              6687       K. Zohore  0.0040

[1774 rows x 2 columns]

**Ejercicio**: Usando las categorías de edad que has definido previamente (Joven, Maduro, Veterano), ¿cuántos jugadores hay en cada categoría de edad agrupados por club?

In [ ]:
(
    df_fifa
    .groupby(['club', 'age_group'])
    .agg(
        count_type=('name', 'count')       
    )
)

                         count_type
club          age_group
1860 München  Joven              10
              Maduro             16
              Veterano            2
9 de Octubre  Maduro              3
              Veterano            1
...                             ...
ŁKS Łódź      Maduro             12
              Veterano            6
Śląsk Wrocław Joven              17
              Maduro             16
              Veterano            2

[2426 rows x 1 columns]

<h3><font color="#00586D" size=4><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Ejercicio</font></h3>

Un problema también muy habitual es el de disponer de los datos en un formato normalizado, en el que la información de las diferentes entidades están divididas en diferentes tablas. En este caso, disponemos de la información de canciones pertenecientes al ranking `bilboard` en el csv `billboard-norm-tracks.csv`, y la información de los puestos en los que entró cada canción en el csv `billboard-norm-ranks.csv`. La forma de combinar ambos dataframes (y de forma general siempre es así) es mediante un ID, en este caso la columna `id`.

Este formato es óptimo para el almacenamiento de la información, ya que no tenemos información duplicada de cada canción junto con su ranking, pero es inmanejable desde el punto de vista analítico. Por ello, en este ejercicio, deberemos combinar ambos `DataFrames` haciendo uso de la función `merge`.

In [ ]:
df_bill_norm_tracks = pd.read_csv(r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\billboard-norm-tracks.csv")
df_bill_norm_ranks = pd.read_csv(r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\billboard-norm-ranks.csv")

display(df_bill_norm_tracks.head(8))
display(df_bill_norm_ranks.head(8))

   id  year                          track         artist  time    genre
0   0  2000     (Hot S**t) Country Grammar          Nelly  4:17      Rap
1   1  2000                 3 Little Words      Nu Flavor  3:54      R&B
2   2  2000                            911   Jean, Wyclef  4:00      Rap
3   3  2000      A Country Boy Can Survive    Brock, Chad  3:54  Country
4   4  2000              A Little Gasoline   Clark, Terri  3:07  Country
5   5  2000  A Puro Dolor (Purest Of Pain)    Son By Four  3:30    Latin
6   6  2000    Aaron's Party (Come Get It)  Carter, Aaron  3:23      R&B
7   7  2000   Absolutely (Story Of A Girl)      Nine Days  3:09     Rock

   id        date   rank
0   0  2000-04-29  100.0
1   0  2000-05-06   99.0
2   0  2000-05-13   96.0
3   0  2000-05-20   76.0
4   0  2000-05-27   55.0
5   0  2000-06-03   37.0
6   0  2000-06-10   24.0
7   0  2000-06-17   24.0

In [ ]:
(
    df_bill_norm_ranks
    .merge(
        df_bill_norm_tracks,
        on=['id']
    )
)

,id,date,rank,year,track,artist,time,genre
0,0,2000-04-29,100.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
1,0,2000-05-06,99.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
2,0,2000-05-13,96.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
3,0,2000-05-20,76.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
4,0,2000-05-27,55.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
...,...,...,...,...,...,...,...,...
5302,316,2001-01-13,63.0,2000,www.memory,"Jackson, Alan",2:36,Country
5303,316,2001-01-20,67.0,2000,www.memory,"Jackson, Alan",2:36,Country
5304,316,2001-01-27,77.0,2000,www.memory,"Jackson, Alan",2:36,Country
5305,316,2001-02-03,89.0,2000,www.memory,"Jackson, Alan",2:36,Country
5306,316,2001-02-10,99.0,2000,www.memory,"Jackson, Alan",2:36,Country

In [ ]:
# Opción 2
pd.merge(
    df_bill_norm_tracks,
    df_bill_norm_ranks,
    on=['id']
)

,id,year,track,artist,time,genre,date,rank
0,0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap,2000-04-29,100.0
1,0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap,2000-05-06,99.0
2,0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap,2000-05-13,96.0
3,0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap,2000-05-20,76.0
4,0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap,2000-05-27,55.0
...,...,...,...,...,...,...,...,...
5302,316,2000,www.memory,"Jackson, Alan",2:36,Country,2001-01-13,63.0
5303,316,2000,www.memory,"Jackson, Alan",2:36,Country,2001-01-20,67.0
5304,316,2000,www.memory,"Jackson, Alan",2:36,Country,2001-01-27,77.0
5305,316,2000,www.memory,"Jackson, Alan",2:36,Country,2001-02-03,89.0
5306,316,2000,www.memory,"Jackson, Alan",2:36,Country,2001-02-10,99.0

In [ ]:
#opción 3 pero con Join

df_bill_norm_ranks.join(
    df_bill_norm_tracks.set_index('id'),
    on='id'
)

,id,date,rank,year,track,artist,time,genre
0,0,2000-04-29,100.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
1,0,2000-05-06,99.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
2,0,2000-05-13,96.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
3,0,2000-05-20,76.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
4,0,2000-05-27,55.0,2000,(Hot S**t) Country Grammar,Nelly,4:17,Rap
...,...,...,...,...,...,...,...,...
5302,316,2001-01-13,63.0,2000,www.memory,"Jackson, Alan",2:36,Country
5303,316,2001-01-20,67.0,2000,www.memory,"Jackson, Alan",2:36,Country
5304,316,2001-01-27,77.0,2000,www.memory,"Jackson, Alan",2:36,Country
5305,316,2001-02-03,89.0,2000,www.memory,"Jackson, Alan",2:36,Country
5306,316,2001-02-10,99.0,2000,www.memory,"Jackson, Alan",2:36,Country

<h3><font color="#00586D" size=4><i class="fa fa-pencil-square-o" aria-hidden="true"></i>Ejercicio</font></h3>

Uno de los problemas más habituales es que nuestros datos están divididos en distintas tablas aun representando el mismo modelo y existe información implícita en la representación, por ejemplo en el nombre de las tablas o los ficheros.

Éste es el caso del dataset `baby-names`, que contiene un estudio sobre la frecuencia de los nombres que se les ponen a los bebes en USA en distintos años. Este dataset viene en un formato que proporciona un fichero por año, donde el año viene especificado en el nombre del fichero.

Este dataset tiene las variables `year`, `rank`, `name`, `frequency` y `sex`, pero la variable year está implícita en los datos (nombre del fichero) y no aparece en el modelo.

Crear una función que se le pase una lista de _paths_, que lea cada uno de los `DataFrames` a partir de cada uno de los paths, y que utilize `pd.concat` para devolver un único `DataFrame`. Además, cada dataframe debe incluir una nueva columna llamada `year` que indique el año representado en el propio nombre (path) del fichero. Para ello será necesario usar la función de strings `split`.

In [ ]:
display( pd.read_csv(r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\2014-baby-names-raw.csv").head(2) )
display( pd.read_csv(r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\2015-baby-names-raw.csv").head(2) )

   rank       name  frequency   sex
0     1       Noah        837  Male
1     2  Alexander        747  Male

   rank  name  frequency   sex
0     1  Noah        863  Male
1     2  Liam        709  Male

In [ ]:
def read_by_year(path):
    name = path.split("/")[-1]
    year = name[:4]
    return (
        pd.read_csv(path)
        .assign(year=year)
    )
def read_baby_names(paths):
    df = (
        pd.concat(
            [read_by_year(path) for path in paths]
        )

    )
    return df

paths = [r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\2014-baby-names-raw.csv", r"C:\Users\edith\OneDrive\Documentos\Universidad\Máster IA\T1-herramientas_programación\notebooks\data\2015-baby-names-raw.csv"]
read_baby_names(paths)

    rank       name  frequency   sex  year
0      1       Noah        837  Male  C:\U
1      2  Alexander        747  Male  C:\U
2      3    William        687  Male  C:\U
3      4    Michael        680  Male  C:\U
4      5       Liam        670  Male  C:\U
..   ...        ...        ...   ...   ...
95    96   Giovanni        168  Male  C:\U
96    97     Hudson        167  Male  C:\U
97    98     Camden        165  Male  C:\U
98    99        Max        164  Male  C:\U
99   100    Maxwell        155  Male  C:\U

[201 rows x 5 columns]